import { GEAR_SLOTS, type GearItem, type ProfileVariant, type SimcProfile } from './types.js';

/** Simulation knobs that become top-level simc option lines. */
export interface SimOptions {
  iterations?: number;
  targetError?: number;
  fightStyle?: string;
  maxTime?: number;
  threads?: number;
  /** Number of enemies for multi-target fight styles. */
  desiredTargets?: number;
  /** Path simc should write its JSON report to. */
  jsonOutput?: string;
  /** Optional `calculate_scale_factors=1` and friends. */
  scaleFactors?: boolean;
}

/**
 * Rebuilds one `slot=name,id=...` line exactly as the addon emits it.
 *
 * The name is left empty by default. We only ever recover names from the
 * comment above each item, and re-emitting one inline both breaks byte-identical
 * round-tripping and risks feeding simc a name containing a comma. The name is
 * preserved in the preceding comment line by `serializeProfile` instead.
 */
export function serializeItem(item: GearItem, includeName = false): string {
  const parts: string[] = [includeName ? (item.name ?? '') : ''];
  parts.push('id=' + item.id);
  if (item.enchantId !== undefined) parts.push('enchant_id=' + item.enchantId);
  if (item.gemIds.length) parts.push('gem_id=' + item.gemIds.join('/'));
  if (item.bonusIds.length) parts.push('bonus_id=' + item.bonusIds.join('/'));
  if (item.craftedStats.length) parts.push('crafted_stats=' + item.craftedStats.join('/'));
  if (item.craftingQuality !== undefined) parts.push('crafting_quality=' + item.craftingQuality);
  if (item.tempEnchantId !== undefined) parts.push('tempenchant_id=' + item.tempEnchantId);
  if (item.contentTuning !== undefined) parts.push('content_tuning=' + item.contentTuning);
  for (const [key, value] of Object.entries(item.extra)) parts.push(key + '=' + value);
  return item.slot + '=' + parts.join(',');
}

/** The talent hash that a given variant should sim with. */
export function resolveTalents(profile: SimcProfile, variant?: ProfileVariant): string | undefined {
  if (variant?.talents) return variant.talents;
  const active = profile.talents.find((t) => t.active);
  return active?.hash ?? profile.talents[0]?.hash;
}

/**
 * Renders a profile (optionally with a variant applied) as simc input text.
 *
 * Only the equipped set is emitted -- bag items are alternates, and simc would
 * reject two `head=` lines. A variant's `gear` map replaces equipped items by
 * slot, which is how gear-comparison runs are built.
 */
export function serializeProfile(
  profile: SimcProfile,
  variant?: ProfileVariant,
  options: SimOptions = {},
): string {
  const lines: string[] = [];
  const label = variant?.label ?? 'baseline';

  lines.push('# Generated by wow-unified-sim -- variant: ' + label);
  if (profile.meta.characterName) {
    lines.push('# Source: ' + profile.meta.characterName + ' (' + (profile.meta.specLabel ?? '?') + ')');
  }
  lines.push('');

  if (profile.class) lines.push(profile.class + '="' + (profile.name ?? 'Character') + '"');
  if (profile.level !== undefined) lines.push('level=' + profile.level);
  if (profile.race) lines.push('race=' + profile.race);
  if (profile.region) lines.push('region=' + profile.region);
  if (profile.server) lines.push('server=' + profile.server);
  if (profile.role) lines.push('role=' + profile.role);
  if (profile.professions && Object.keys(profile.professions).length) {
    const professions = Object.entries(profile.professions)
      .map(([name, rank]) => name + '=' + rank)
      .join('/');
    lines.push('professions=' + professions);
  }
  if (profile.spec) lines.push('spec=' + profile.spec);

  const talents = resolveTalents(profile, variant);
  if (talents) lines.push('talents=' + talents);

  if (Object.keys(profile.omniumTalents).length) {
    const omnium = Object.entries(profile.omniumTalents)
      .map(([id, rank]) => id + ':' + rank)
      .join('/');
    lines.push('omnium_talents=' + omnium);
  }

  for (const [key, value] of Object.entries(profile.unknownOptions)) {
    lines.push(key + '=' + value);
  }

  lines.push('');

  const gear = { ...profile.equipped, ...(variant?.gear ?? {}) };
  for (const slot of GEAR_SLOTS) {
    const item = gear[slot];
    if (!item || !item.id) continue;
    if (item.name || item.itemLevel !== undefined) {
      lines.push('# ' + (item.name ?? 'Unknown') + (item.itemLevel ? ' (' + item.itemLevel + ')' : ''));
    }
    lines.push(serializeItem({ ...item, slot }));
  }

  const simLines = serializeSimOptions(options);
  if (simLines.length) {
    lines.push('');
    lines.push('# --- simulation options ---');
    lines.push(...simLines);
  }

  if (variant?.extraOptions?.length) {
    lines.push('');
    lines.push('# --- variant options ---');
    lines.push(...variant.extraOptions);
  }

  return lines.join('\n') + '\n';
}

/** Sim knobs rendered as standalone simc option lines. */
export function serializeSimOptions(options: SimOptions): string[] {
  const lines: string[] = [];
  if (options.iterations !== undefined) lines.push('iterations=' + options.iterations);
  if (options.targetError !== undefined) lines.push('target_error=' + options.targetError);
  if (options.fightStyle) lines.push('fight_style=' + options.fightStyle);
  if (options.maxTime !== undefined) lines.push('max_time=' + options.maxTime);
  if (options.desiredTargets !== undefined) lines.push('desired_targets=' + options.desiredTargets);
  if (options.threads !== undefined) lines.push('threads=' + options.threads);
  if (options.scaleFactors) lines.push('calculate_scale_factors=1');
  if (options.jsonOutput) lines.push('json2=' + options.jsonOutput);
  return lines;
}
